# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

r_binary_packages:
  - covr

jobs:
  include:
    - stage: "R CMD check"
      name: "Old Release"
      r: oldrel

    - name: "Release"
      r: release
      after_success:
        - Rscript -e 'covr::codecov()'
      before_cache:
        - Rscript -e 'remotes::install_cran("pkgdown")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
        on:
          branch: master
          repo: rstudio/sortable

    - name: "Devel"
      r: devel
