# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

matrix:
  include:

  - name: "Release"
    r: release
    before_cache:
    - Rscript -e 'remotes::install_cran("covr")'
    after_success:
    - Rscript -e 'covr::codecov()'
    - find . -name testthat.Rout | xargs cat
    after_failure:
    - find . -name testthat.Rout | xargs cat

  - name: "Old Release"
    r: oldrel

  - name: "Devel"
    r: devel


  - stage: "Deploy"
    if: branch IN (master, travis) AND repo = rstudio/sortable
    name: "Tutorials"
    r: release
    warnings_are_errors: false
    before_cache:
    - Rscript -e 'remotes::install_cran("rsconnect")'
    - Rscript -e 'remotes::install_cran("here")'
    - Rscript -e 'remotes::install_cran("glue")'
    - Rscript -e 'remotes::install_cran("remotes")'
    script:
    - R -f scripts/deploy_tutorial.R

  - name: "gh-pages"
    r_binary_packages:
    - pkgdown
    script:
    - Rscript -e "remotes::install_local()"
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
