# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

jobs:
  include:
    - stage: "R CMD check"
      name: "Old Release"
      r: oldrel

    - name: "Release"
      r: release

    - name: "Devel"
      r: devel

    - name: "covr; lintr; deploy gh-pages"
      r: release
      r_binary_packages:
        - covr
        - pkgdown
      script:
        - Rscript -e 'covr::codecov()'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
        on:
          branch: master
          repo: rstudio/sortable
